# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QGridLayout, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QToolBar, QWidget)

from zlabel.widgets.canvas import Canvas
from zlabel.widgets.dock_anno import ZDockAnnotationContent
from zlabel.widgets.dock_file import ZDockFileContent
from zlabel.widgets.dock_info import ZDockInfoContent
from zlabel.widgets.dock_label import ZDockLabelContent
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1034, 727)
        MainWindow.setMinimumSize(QSize(800, 600))
        font = QFont()
        font.setFamilies([u"Times New Roman"])
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icon/icons/logo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpen_dir = QAction(MainWindow)
        self.actionOpen_dir.setObjectName(u"actionOpen_dir")
        self.actionOpen_dir.setEnabled(False)
        icon1 = QIcon()
        icon1.addFile(u":/icon/icons/pic.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen_dir.setIcon(icon1)
        self.actionZoom_in = QAction(MainWindow)
        self.actionZoom_in.setObjectName(u"actionZoom_in")
        icon2 = QIcon()
        icon2.addFile(u":/icon/icons/zoom-in.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoom_in.setIcon(icon2)
        self.actionMagnifier = QAction(MainWindow)
        self.actionMagnifier.setObjectName(u"actionMagnifier")
        self.actionMagnifier.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/icon/icons/magnifier.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMagnifier.setIcon(icon3)
        self.actionZoom_out = QAction(MainWindow)
        self.actionZoom_out.setObjectName(u"actionZoom_out")
        icon4 = QIcon()
        icon4.addFile(u":/icon/icons/zoom-out.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoom_out.setIcon(icon4)
        self.actionFit_wiondow = QAction(MainWindow)
        self.actionFit_wiondow.setObjectName(u"actionFit_wiondow")
        self.actionFit_wiondow.setEnabled(True)
        icon5 = QIcon()
        icon5.addFile(u":/icon/icons/fullwidth.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFit_wiondow.setIcon(icon5)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon6 = QIcon()
        icon6.addFile(u":/icon/icons/setting-two.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSettings.setIcon(icon6)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon7 = QIcon()
        icon7.addFile(u":/icon/icons/power.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon7)
        self.actionSave_dir = QAction(MainWindow)
        self.actionSave_dir.setObjectName(u"actionSave_dir")
        self.actionSave_dir.setEnabled(False)
        icon8 = QIcon()
        icon8.addFile(u":/icon/icons/folder-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_dir.setIcon(icon8)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon9 = QIcon()
        icon9.addFile(u":/icon/icons/save.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon9)
        self.actionPrev = QAction(MainWindow)
        self.actionPrev.setObjectName(u"actionPrev")
        self.actionPrev.setCheckable(False)
        icon10 = QIcon()
        icon10.addFile(u":/icon/icons/prev.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrev.setIcon(icon10)
        self.actionPrev.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionPrev.setPriority(QAction.Priority.NormalPriority)
        self.actionNext = QAction(MainWindow)
        self.actionNext.setObjectName(u"actionNext")
        icon11 = QIcon()
        icon11.addFile(u":/icon/icons/next.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNext.setIcon(icon11)
        self.actionShortcut = QAction(MainWindow)
        self.actionShortcut.setObjectName(u"actionShortcut")
        icon12 = QIcon()
        icon12.addFile(u":/icon/icons/keyboard-one.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShortcut.setIcon(icon12)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon13 = QIcon()
        icon13.addFile(u":/icon/icons/me.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout.setIcon(icon13)
        self.actionSAM = QAction(MainWindow)
        self.actionSAM.setObjectName(u"actionSAM")
        self.actionSAM.setCheckable(True)
        icon14 = QIcon()
        icon14.addFile(u":/icon/icons/M_Favicon.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSAM.setIcon(icon14)
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDelete.setEnabled(False)
        icon15 = QIcon()
        icon15.addFile(u":/icon/icons/delete-3.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete.setIcon(icon15)
        self.actionBit_map = QAction(MainWindow)
        self.actionBit_map.setObjectName(u"actionBit_map")
        self.actionBit_map.setCheckable(False)
        self.actionBit_map.setIcon(icon1)
        self.actionTo_top = QAction(MainWindow)
        self.actionTo_top.setObjectName(u"actionTo_top")
        self.actionTo_top.setEnabled(False)
        icon16 = QIcon()
        icon16.addFile(u":/icon/icons/to-top.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTo_top.setIcon(icon16)
        self.actionTo_bottom = QAction(MainWindow)
        self.actionTo_bottom.setObjectName(u"actionTo_bottom")
        self.actionTo_bottom.setEnabled(False)
        icon17 = QIcon()
        icon17.addFile(u":/icon/icons/to-bottom.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTo_bottom.setIcon(icon17)
        self.actionToVOC = QAction(MainWindow)
        self.actionToVOC.setObjectName(u"actionToVOC")
        icon18 = QIcon()
        icon18.addFile(u":/icon/icons/VOC_32x32.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionToVOC.setIcon(icon18)
        self.actionBackspace = QAction(MainWindow)
        self.actionBackspace.setObjectName(u"actionBackspace")
        icon19 = QIcon()
        icon19.addFile(u":/icon/icons/delete-two.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBackspace.setIcon(icon19)
        self.actionCancel = QAction(MainWindow)
        self.actionCancel.setObjectName(u"actionCancel")
        icon20 = QIcon()
        icon20.addFile(u":/icon/icons/close-one.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCancel.setIcon(icon20)
        self.actionFinish = QAction(MainWindow)
        self.actionFinish.setObjectName(u"actionFinish")
        icon21 = QIcon()
        icon21.addFile(u":/icon/icons/check-one.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFinish.setIcon(icon21)
        self.actionPolygon = QAction(MainWindow)
        self.actionPolygon.setObjectName(u"actionPolygon")
        self.actionPolygon.setEnabled(True)
        icon22 = QIcon()
        icon22.addFile(u":/icon/icons/polygon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPolygon.setIcon(icon22)
        self.actionVisible = QAction(MainWindow)
        self.actionVisible.setObjectName(u"actionVisible")
        self.actionVisible.setCheckable(True)
        self.actionVisible.setChecked(True)
        icon23 = QIcon()
        icon23.addFile(u":/icon/icons/eye-2.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionVisible.setIcon(icon23)
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        icon24 = QIcon()
        icon24.addFile(u":/icon/icons/efferent-three.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport.setIcon(icon24)
        self.action_copy_prev = QAction(MainWindow)
        self.action_copy_prev.setObjectName(u"action_copy_prev")
        icon25 = QIcon()
        icon25.addFile(u":/icon/icons/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_copy_prev.setIcon(icon25)
        self.action_import_task = QAction(MainWindow)
        self.action_import_task.setObjectName(u"action_import_task")
        icon26 = QIcon()
        icon26.addFile(u":/icon/icons/afferent-three.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_import_task.setIcon(icon26)
        self.actionTo_LabelMe = QAction(MainWindow)
        self.actionTo_LabelMe.setObjectName(u"actionTo_LabelMe")
        icon27 = QIcon()
        icon27.addFile(u":/icon/icons/labelme_32x32.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTo_LabelMe.setIcon(icon27)
        self.actionContour_Max_only = QAction(MainWindow)
        self.actionContour_Max_only.setObjectName(u"actionContour_Max_only")
        self.actionContour_Max_only.setCheckable(True)
        self.actionContour_Max_only.setFont(font)
        self.actionContour_External = QAction(MainWindow)
        self.actionContour_External.setObjectName(u"actionContour_External")
        self.actionContour_External.setCheckable(True)
        self.actionContour_External.setFont(font)
        self.actionContour_All = QAction(MainWindow)
        self.actionContour_All.setObjectName(u"actionContour_All")
        self.actionContour_All.setCheckable(True)
        self.actionContour_All.setFont(font)
        self.actionModel_manage = QAction(MainWindow)
        self.actionModel_manage.setObjectName(u"actionModel_manage")
        icon28 = QIcon()
        icon28.addFile(u":/icon/icons/list-middle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionModel_manage.setIcon(icon28)
        self.actionModel_manage.setFont(font)
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        icon29 = QIcon()
        icon29.addFile(u":/icon/icons/rectangle_two_points.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRectangle.setIcon(icon29)
        self.actionPoint = QAction(MainWindow)
        self.actionPoint.setObjectName(u"actionPoint")
        icon30 = QIcon()
        icon30.addFile(u":/icon/icons/three_dots.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPoint.setIcon(icon30)
        self.actionMove = QAction(MainWindow)
        self.actionMove.setObjectName(u"actionMove")
        self.actionMove.setCheckable(False)
        self.actionMove.setEnabled(False)
        icon31 = QIcon()
        icon31.addFile(u":/icon/icons/mouse_pointer.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMove.setIcon(icon31)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        icon32 = QIcon()
        icon32.addFile(u":/icon/icons/edit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEdit.setIcon(icon32)
        self.actionTimeline = QAction(MainWindow)
        self.actionTimeline.setObjectName(u"actionTimeline")
        self.actionTimeline.setCheckable(True)
        self.actionTimeline.setChecked(True)
        icon33 = QIcon()
        icon33.addFile(u":/icon/icons/timeline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTimeline.setIcon(icon33)
        self.actionTimeline.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionOpenCV = QAction(MainWindow)
        self.actionOpenCV.setObjectName(u"actionOpenCV")
        self.actionOpenCV.setCheckable(True)
        icon34 = QIcon()
        icon34.addFile(u":/icon/icons/opencv.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenCV.setIcon(icon34)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon35 = QIcon()
        icon35.addFile(u":/icon/icons/undo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUndo.setIcon(icon35)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon36 = QIcon()
        icon36.addFile(u":/icon/icons/redo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRedo.setIcon(icon36)
        self.actionNew_Project = QAction(MainWindow)
        self.actionNew_Project.setObjectName(u"actionNew_Project")
        self.actionR = QAction(MainWindow)
        self.actionR.setObjectName(u"actionR")
        self.actionR.setCheckable(True)
        self.actionR.setChecked(False)
        self.actionR.setEnabled(True)
        icon37 = QIcon()
        icon37.addFile(u":/icon/icons/channel_r.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionR.setIcon(icon37)
        self.actionR.setText(u"R")
        self.actionG = QAction(MainWindow)
        self.actionG.setObjectName(u"actionG")
        self.actionG.setCheckable(True)
        self.actionG.setEnabled(True)
        icon38 = QIcon()
        icon38.addFile(u":/icon/icons/channel_g.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionG.setIcon(icon38)
        self.actionG.setText(u"G")
        self.actionB = QAction(MainWindow)
        self.actionB.setObjectName(u"actionB")
        self.actionB.setCheckable(True)
        self.actionB.setEnabled(True)
        icon39 = QIcon()
        icon39.addFile(u":/icon/icons/channel_b.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionB.setIcon(icon39)
        self.actionB.setText(u"B")
        self.actionRGB = QAction(MainWindow)
        self.actionRGB.setObjectName(u"actionRGB")
        self.actionRGB.setCheckable(True)
        self.actionRGB.setChecked(True)
        icon40 = QIcon()
        icon40.addFile(u":/icon/icons/channel.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRGB.setIcon(icon40)
        self.actionRGB.setText(u"RGB")
        self.actionGray = QAction(MainWindow)
        self.actionGray.setObjectName(u"actionGray")
        self.actionGray.setCheckable(True)
        self.actionGray.setEnabled(True)
        icon41 = QIcon()
        icon41.addFile(u":/icon/icons/channel_gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGray.setIcon(icon41)
        self.actionGray.setText(u"Gray")
        self.actionMerge = QAction(MainWindow)
        self.actionMerge.setObjectName(u"actionMerge")
        icon42 = QIcon()
        icon42.addFile(u":/icon/icons/merge.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMerge.setIcon(icon42)
        self.actionGroup = QAction(MainWindow)
        self.actionGroup.setObjectName(u"actionGroup")
        self.actionGroup.setCheckable(True)
        icon43 = QIcon()
        icon43.addFile(u":/icon/icons/group.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGroup.setIcon(icon43)
        self.actionAnnoTypeRectangle = QAction(MainWindow)
        self.actionAnnoTypeRectangle.setObjectName(u"actionAnnoTypeRectangle")
        self.actionAnnoTypeRectangle.setEnabled(True)
        self.actionAnnoTypeRectangle.setIcon(icon29)
        self.actionAnnoTypePolygon = QAction(MainWindow)
        self.actionAnnoTypePolygon.setObjectName(u"actionAnnoTypePolygon")
        self.actionAnnoTypePolygon.setEnabled(True)
        icon44 = QIcon()
        icon44.addFile(u":/icon/icons/polygon_0.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnnoTypePolygon.setIcon(icon44)
        self.actionAnnoTypeRLEMask = QAction(MainWindow)
        self.actionAnnoTypeRLEMask.setObjectName(u"actionAnnoTypeRLEMask")
        self.actionAnnoTypeRLEMask.setEnabled(False)
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionChinese = QAction(MainWindow)
        self.actionChinese.setObjectName(u"actionChinese")
        self.actionFiles = QAction(MainWindow)
        self.actionFiles.setObjectName(u"actionFiles")
        self.actionFiles.setCheckable(True)
        self.actionFiles.setChecked(True)
        icon45 = QIcon()
        icon45.addFile(u":/icon/icons/file.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFiles.setIcon(icon45)
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionInfo.setCheckable(True)
        self.actionInfo.setChecked(True)
        icon46 = QIcon()
        icon46.addFile(u":/icon/icons/info.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionInfo.setIcon(icon46)
        self.actionAnnotations = QAction(MainWindow)
        self.actionAnnotations.setObjectName(u"actionAnnotations")
        self.actionAnnotations.setCheckable(True)
        self.actionAnnotations.setChecked(True)
        icon47 = QIcon()
        icon47.addFile(u":/icon/icons/annotate.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAnnotations.setIcon(icon47)
        self.actionLabels = QAction(MainWindow)
        self.actionLabels.setObjectName(u"actionLabels")
        self.actionLabels.setCheckable(True)
        self.actionLabels.setChecked(True)
        icon48 = QIcon()
        icon48.addFile(u":/icon/icons/label.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLabels.setIcon(icon48)
        self.actionRestore = QAction(MainWindow)
        self.actionRestore.setObjectName(u"actionRestore")
        icon49 = QIcon()
        icon49.addFile(u":/icon/icons/reset.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRestore.setIcon(icon49)
        self.actionFullScreen = QAction(MainWindow)
        self.actionFullScreen.setObjectName(u"actionFullScreen")
        self.actionFullScreen.setCheckable(True)
        icon50 = QIcon()
        icon50.addFile(u":/icon/icons/fullscreen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFullScreen.setIcon(icon50)
        self.actionAnnoTypeKeyPoint = QAction(MainWindow)
        self.actionAnnoTypeKeyPoint.setObjectName(u"actionAnnoTypeKeyPoint")
        self.actionAnnoTypeKeyPoint.setIcon(icon30)
        self.actionDockLeft = QAction(MainWindow)
        self.actionDockLeft.setObjectName(u"actionDockLeft")
        self.actionDockLeft.setCheckable(True)
        self.actionDockLeft.setChecked(True)
        icon51 = QIcon()
        icon51.addFile(u":/icon/icons/dock_left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDockLeft.setIcon(icon51)
        self.actionDockRight = QAction(MainWindow)
        self.actionDockRight.setObjectName(u"actionDockRight")
        self.actionDockRight.setCheckable(True)
        self.actionDockRight.setChecked(True)
        icon52 = QIcon()
        icon52.addFile(u":/icon/icons/dock_right.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDockRight.setIcon(icon52)
        self.actionDockBottom = QAction(MainWindow)
        self.actionDockBottom.setObjectName(u"actionDockBottom")
        self.actionDockBottom.setCheckable(True)
        self.actionDockBottom.setChecked(True)
        icon53 = QIcon()
        icon53.addFile(u":/icon/icons/dock_bottom.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDockBottom.setIcon(icon53)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.canvas = Canvas(self.centralwidget)
        self.canvas.setObjectName(u"canvas")

        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QRect(0, 0, 1034, 33))
        self.menubar.setFont(font)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setFont(font)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuView.setFont(font)
        self.menuView.setSeparatorsCollapsible(False)
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setFont(font)
        self.menuLang = QMenu(self.menuAbout)
        self.menuLang.setObjectName(u"menuLang")
        icon54 = QIcon()
        icon54.addFile(u":/icon/icons/translate.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.menuLang.setIcon(icon54)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuEdit.setFont(font)
        self.menuAnno_Type = QMenu(self.menuEdit)
        self.menuAnno_Type.setObjectName(u"menuAnno_Type")
        self.menuAnno_Type.setEnabled(True)
        self.menuAnno_Type.setIcon(icon47)
        self.menuAnno_Type.setToolTipsVisible(True)
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuDocks = QMenu(self.menuWindow)
        self.menuDocks.setObjectName(u"menuDocks")
        self.menuDocks.setIcon(icon53)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setFont(font)
        self.toolBar.setIconSize(QSize(24, 24))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dock_infos = QDockWidget(MainWindow)
        self.dock_infos.setObjectName(u"dock_infos")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dock_infos.sizePolicy().hasHeightForWidth())
        self.dock_infos.setSizePolicy(sizePolicy)
        self.dock_infos.setAcceptDrops(False)
        self.dockcnt_info = ZDockInfoContent()
        self.dockcnt_info.setObjectName(u"dockcnt_info")
        self.dock_infos.setWidget(self.dockcnt_info)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dock_infos)
        self.dock_annos = QDockWidget(MainWindow)
        self.dock_annos.setObjectName(u"dock_annos")
        sizePolicy.setHeightForWidth(self.dock_annos.sizePolicy().hasHeightForWidth())
        self.dock_annos.setSizePolicy(sizePolicy)
        self.dockcnt_anno = ZDockAnnotationContent()
        self.dockcnt_anno.setObjectName(u"dockcnt_anno")
        self.dock_annos.setWidget(self.dockcnt_anno)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dock_annos)
        self.dock_files = QDockWidget(MainWindow)
        self.dock_files.setObjectName(u"dock_files")
        self.dockcnt_files = ZDockFileContent()
        self.dockcnt_files.setObjectName(u"dockcnt_files")
        self.dock_files.setWidget(self.dockcnt_files)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dock_files)
        self.dock_labels = QDockWidget(MainWindow)
        self.dock_labels.setObjectName(u"dock_labels")
        sizePolicy.setHeightForWidth(self.dock_labels.sizePolicy().hasHeightForWidth())
        self.dock_labels.setSizePolicy(sizePolicy)
        self.dock_labels.setFloating(False)
        self.dock_labels.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dock_labels.setAllowedAreas(Qt.DockWidgetArea.AllDockWidgetAreas)
        self.dockcnt_labels = ZDockLabelContent()
        self.dockcnt_labels.setObjectName(u"dockcnt_labels")
        self.dock_labels.setWidget(self.dockcnt_labels)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dock_labels)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.action_import_task)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrev)
        self.menuFile.addAction(self.actionNext)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionFit_wiondow)
        self.menuView.addAction(self.actionFullScreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionR)
        self.menuView.addAction(self.actionG)
        self.menuView.addAction(self.actionB)
        self.menuView.addAction(self.actionRGB)
        self.menuView.addAction(self.actionGray)
        self.menuAbout.addAction(self.menuLang.menuAction())
        self.menuAbout.addAction(self.actionShortcut)
        self.menuAbout.addAction(self.actionAbout)
        self.menuLang.addAction(self.actionEnglish)
        self.menuLang.addAction(self.actionChinese)
        self.menuEdit.addAction(self.menuAnno_Type.menuAction())
        self.menuEdit.addAction(self.actionSAM)
        self.menuEdit.addAction(self.actionOpenCV)
        self.menuEdit.addAction(self.actionMove)
        self.menuEdit.addAction(self.actionEdit)
        self.menuEdit.addAction(self.actionRectangle)
        self.menuEdit.addAction(self.actionPoint)
        self.menuEdit.addAction(self.actionPolygon)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFinish)
        self.menuEdit.addAction(self.actionCancel)
        self.menuEdit.addAction(self.actionSave)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionGroup)
        self.menuEdit.addAction(self.actionMerge)
        self.menuAnno_Type.addAction(self.actionAnnoTypeRectangle)
        self.menuAnno_Type.addAction(self.actionAnnoTypePolygon)
        self.menuAnno_Type.addAction(self.actionAnnoTypeKeyPoint)
        self.menuWindow.addAction(self.menuDocks.menuAction())
        self.menuWindow.addAction(self.actionRestore)
        self.menuDocks.addAction(self.actionFiles)
        self.menuDocks.addAction(self.actionInfo)
        self.menuDocks.addAction(self.actionAnnotations)
        self.menuDocks.addAction(self.actionLabels)
        self.menuDocks.addAction(self.actionTimeline)
        self.menuDocks.addSeparator()
        self.menuDocks.addAction(self.actionDockLeft)
        self.menuDocks.addAction(self.actionDockRight)
        self.menuDocks.addAction(self.actionDockBottom)
        self.toolBar.addAction(self.actionPrev)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSAM)
        self.toolBar.addAction(self.actionOpenCV)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMove)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionRectangle)
        self.toolBar.addAction(self.actionPoint)
        self.toolBar.addAction(self.actionPolygon)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionGroup)
        self.toolBar.addAction(self.actionMerge)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFinish)
        self.toolBar.addAction(self.actionCancel)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMagnifier)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionFit_wiondow)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFullScreen)
        self.toolBar.addAction(self.actionDockLeft)
        self.toolBar.addAction(self.actionDockRight)
        self.toolBar.addAction(self.actionDockBottom)
        self.toolBar.addAction(self.actionVisible)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_copy_prev)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ZLabel", None))
        self.actionOpen_dir.setText(QCoreApplication.translate("MainWindow", u"Images dir", None))
#if QT_CONFIG(statustip)
        self.actionOpen_dir.setStatusTip(QCoreApplication.translate("MainWindow", u"Open images dir.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOpen_dir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_in.setText(QCoreApplication.translate("MainWindow", u"Zoom in", None))
#if QT_CONFIG(statustip)
        self.actionZoom_in.setStatusTip(QCoreApplication.translate("MainWindow", u"Zoom in.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionZoom_in.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.actionMagnifier.setText(QCoreApplication.translate("MainWindow", u"Magnifier", None))
#if QT_CONFIG(tooltip)
        self.actionMagnifier.setToolTip(QCoreApplication.translate("MainWindow", u"Magnifier (Ctrl+M)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMagnifier.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_out.setText(QCoreApplication.translate("MainWindow", u"Zoom out", None))
#if QT_CONFIG(statustip)
        self.actionZoom_out.setStatusTip(QCoreApplication.translate("MainWindow", u"Zoom out.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionZoom_out.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionFit_wiondow.setText(QCoreApplication.translate("MainWindow", u"Fit window", None))
#if QT_CONFIG(tooltip)
        self.actionFit_wiondow.setToolTip(QCoreApplication.translate("MainWindow", u"Fit window", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionFit_wiondow.setStatusTip(QCoreApplication.translate("MainWindow", u"Fit window.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionFit_wiondow.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Setting", None))
#if QT_CONFIG(statustip)
        self.actionSettings.setStatusTip(QCoreApplication.translate("MainWindow", u"Setting.", None))
#endif // QT_CONFIG(statustip)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionExit.setStatusTip(QCoreApplication.translate("MainWindow", u"Exit.", None))
#endif // QT_CONFIG(statustip)
        self.actionSave_dir.setText(QCoreApplication.translate("MainWindow", u"Save dir", None))
        self.actionSave_dir.setIconText(QCoreApplication.translate("MainWindow", u"Save dir", None))
#if QT_CONFIG(statustip)
        self.actionSave_dir.setStatusTip(QCoreApplication.translate("MainWindow", u"Select Save dir", None))
#endif // QT_CONFIG(statustip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save Project (Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"Save Project", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrev.setText(QCoreApplication.translate("MainWindow", u"Prev image", None))
#if QT_CONFIG(tooltip)
        self.actionPrev.setToolTip(QCoreApplication.translate("MainWindow", u"Prev image (A)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPrev.setStatusTip(QCoreApplication.translate("MainWindow", u"Prev image (A)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionPrev.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext.setText(QCoreApplication.translate("MainWindow", u"Next image", None))
#if QT_CONFIG(tooltip)
        self.actionNext.setToolTip(QCoreApplication.translate("MainWindow", u"Next image (D)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionNext.setStatusTip(QCoreApplication.translate("MainWindow", u"Next image (D)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNext.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.actionShortcut.setText(QCoreApplication.translate("MainWindow", u"Shortcut", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionSAM.setText(QCoreApplication.translate("MainWindow", u"SAM", None))
#if QT_CONFIG(tooltip)
        self.actionSAM.setToolTip(QCoreApplication.translate("MainWindow", u"SAM (Q)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSAM.setStatusTip(QCoreApplication.translate("MainWindow", u"SAM (Q)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSAM.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(tooltip)
        self.actionDelete.setToolTip(QCoreApplication.translate("MainWindow", u"Delete polygon", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionDelete.setStatusTip(QCoreApplication.translate("MainWindow", u"Delete polygon.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionBit_map.setText(QCoreApplication.translate("MainWindow", u"Bit map", None))
#if QT_CONFIG(statustip)
        self.actionBit_map.setStatusTip(QCoreApplication.translate("MainWindow", u"Show instance or segmeent state.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionBit_map.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionTo_top.setText(QCoreApplication.translate("MainWindow", u"To top", None))
#if QT_CONFIG(tooltip)
        self.actionTo_top.setToolTip(QCoreApplication.translate("MainWindow", u"Move polygon to top layer", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionTo_top.setStatusTip(QCoreApplication.translate("MainWindow", u"Move polygon to top layer.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionTo_top.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.actionTo_bottom.setText(QCoreApplication.translate("MainWindow", u"To bottom", None))
#if QT_CONFIG(tooltip)
        self.actionTo_bottom.setToolTip(QCoreApplication.translate("MainWindow", u"Move polygon to bottom layer", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionTo_bottom.setStatusTip(QCoreApplication.translate("MainWindow", u"Move polygon to bottom layer.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionTo_bottom.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.actionToVOC.setText(QCoreApplication.translate("MainWindow", u"To VOC", None))
#if QT_CONFIG(tooltip)
        self.actionToVOC.setToolTip(QCoreApplication.translate("MainWindow", u"Convert ISAT to VOC", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionToVOC.setStatusTip(QCoreApplication.translate("MainWindow", u"Convert ISAT jsons to VOC png images.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionToVOC.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.actionBackspace.setText(QCoreApplication.translate("MainWindow", u"Backspace", None))
#if QT_CONFIG(tooltip)
        self.actionBackspace.setToolTip(QCoreApplication.translate("MainWindow", u"Backspace", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionBackspace.setStatusTip(QCoreApplication.translate("MainWindow", u"Backspace.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionBackspace.setShortcut(QCoreApplication.translate("MainWindow", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.actionCancel.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
#if QT_CONFIG(tooltip)
        self.actionCancel.setToolTip(QCoreApplication.translate("MainWindow", u"Clear All (Ctrl+Del)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionCancel.setStatusTip(QCoreApplication.translate("MainWindow", u"Clear All (Ctrl+Del)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionCancel.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionFinish.setText(QCoreApplication.translate("MainWindow", u"Finish", None))
#if QT_CONFIG(tooltip)
        self.actionFinish.setToolTip(QCoreApplication.translate("MainWindow", u"Submit (Ctrl + Enter)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionFinish.setStatusTip(QCoreApplication.translate("MainWindow", u"Annotate finished.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionFinish.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.actionPolygon.setText(QCoreApplication.translate("MainWindow", u"Polygon", None))
#if QT_CONFIG(tooltip)
        self.actionPolygon.setToolTip(QCoreApplication.translate("MainWindow", u"Draw polygon (O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPolygon.setStatusTip(QCoreApplication.translate("MainWindow", u"Accurately annotate by drawing polygon.  (O)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionPolygon.setShortcut(QCoreApplication.translate("MainWindow", u"O", None))
#endif // QT_CONFIG(shortcut)
        self.actionVisible.setText(QCoreApplication.translate("MainWindow", u"Visible", None))
#if QT_CONFIG(tooltip)
        self.actionVisible.setToolTip(QCoreApplication.translate("MainWindow", u"Visible", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionVisible.setStatusTip(QCoreApplication.translate("MainWindow", u"Visible.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionVisible.setShortcut(QCoreApplication.translate("MainWindow", u"V", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(tooltip)
        self.actionExport.setToolTip(QCoreApplication.translate("MainWindow", u"Convert ISAT to COCO", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionExport.setStatusTip(QCoreApplication.translate("MainWindow", u"Convert ISAT jsons to COCO json.", None))
#endif // QT_CONFIG(statustip)
        self.action_copy_prev.setText(QCoreApplication.translate("MainWindow", u"Copy previous frame", None))
#if QT_CONFIG(tooltip)
        self.action_copy_prev.setToolTip(QCoreApplication.translate("MainWindow", u"Copy previous frame", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_copy_prev.setStatusTip(QCoreApplication.translate("MainWindow", u"Copy dish/timestamp/instance parts from the previous frame of the same sequence", None))
#endif // QT_CONFIG(statustip)
        self.action_import_task.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionTo_LabelMe.setText(QCoreApplication.translate("MainWindow", u"To LabelMe", None))
#if QT_CONFIG(tooltip)
        self.actionTo_LabelMe.setToolTip(QCoreApplication.translate("MainWindow", u"Convert ISAT to LabelMe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionTo_LabelMe.setStatusTip(QCoreApplication.translate("MainWindow", u"Convert ISAT jsons to LabelMe jsons.", None))
#endif // QT_CONFIG(statustip)
        self.actionContour_Max_only.setText(QCoreApplication.translate("MainWindow", u"Max only", None))
#if QT_CONFIG(statustip)
        self.actionContour_Max_only.setStatusTip(QCoreApplication.translate("MainWindow", u"Max contour save only.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionContour_Max_only.setWhatsThis(QCoreApplication.translate("MainWindow", u"Max contour save only.", None))
#endif // QT_CONFIG(whatsthis)
        self.actionContour_External.setText(QCoreApplication.translate("MainWindow", u"External", None))
#if QT_CONFIG(statustip)
        self.actionContour_External.setStatusTip(QCoreApplication.translate("MainWindow", u"External contour save only.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionContour_External.setWhatsThis(QCoreApplication.translate("MainWindow", u"External contour save only.", None))
#endif // QT_CONFIG(whatsthis)
        self.actionContour_All.setText(QCoreApplication.translate("MainWindow", u"All", None))
#if QT_CONFIG(statustip)
        self.actionContour_All.setStatusTip(QCoreApplication.translate("MainWindow", u"All contour save.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionContour_All.setWhatsThis(QCoreApplication.translate("MainWindow", u"All contour save.", None))
#endif // QT_CONFIG(whatsthis)
        self.actionModel_manage.setText(QCoreApplication.translate("MainWindow", u"Model manage", None))
#if QT_CONFIG(statustip)
        self.actionModel_manage.setStatusTip(QCoreApplication.translate("MainWindow", u"Model manage.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionModel_manage.setWhatsThis(QCoreApplication.translate("MainWindow", u"Model manage.", None))
#endif // QT_CONFIG(whatsthis)
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
#if QT_CONFIG(tooltip)
        self.actionRectangle.setToolTip(QCoreApplication.translate("MainWindow", u"Rectangle (R)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionRectangle.setStatusTip(QCoreApplication.translate("MainWindow", u"Create Two-point Rectangle (R)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionRectangle.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.actionPoint.setText(QCoreApplication.translate("MainWindow", u"Point", None))
#if QT_CONFIG(tooltip)
        self.actionPoint.setToolTip(QCoreApplication.translate("MainWindow", u"Point (P)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPoint.setStatusTip(QCoreApplication.translate("MainWindow", u"Create a point (P)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionPoint.setShortcut(QCoreApplication.translate("MainWindow", u"P", None))
#endif // QT_CONFIG(shortcut)
        self.actionMove.setText(QCoreApplication.translate("MainWindow", u"Move", None))
#if QT_CONFIG(tooltip)
        self.actionMove.setToolTip(QCoreApplication.translate("MainWindow", u"Move (M)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionMove.setStatusTip(QCoreApplication.translate("MainWindow", u"Move to select a region (M)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionMove.setShortcut(QCoreApplication.translate("MainWindow", u"M", None))
#endif // QT_CONFIG(shortcut)
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
#if QT_CONFIG(tooltip)
        self.actionEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Edit (E)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionEdit.setStatusTip(QCoreApplication.translate("MainWindow", u"Edit (E)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionEdit.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
        self.actionTimeline.setText(QCoreApplication.translate("MainWindow", u"Timeline", None))
#if QT_CONFIG(tooltip)
        self.actionTimeline.setToolTip(QCoreApplication.translate("MainWindow", u"Timeline", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpenCV.setText(QCoreApplication.translate("MainWindow", u"OpenCV", None))
#if QT_CONFIG(tooltip)
        self.actionOpenCV.setToolTip(QCoreApplication.translate("MainWindow", u"OpenCV (W)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpenCV.setStatusTip(QCoreApplication.translate("MainWindow", u"Enable OpenCV (W)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOpenCV.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Project.setText(QCoreApplication.translate("MainWindow", u"New Project", None))
        self.actionMerge.setText(QCoreApplication.translate("MainWindow", u"Merge", None))
#if QT_CONFIG(tooltip)
        self.actionMerge.setToolTip(QCoreApplication.translate("MainWindow", u"Merge (G)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionMerge.setStatusTip(QCoreApplication.translate("MainWindow", u"Merge multiple shapes (G)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionMerge.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.actionGroup.setText(QCoreApplication.translate("MainWindow", u"Group", None))
#if QT_CONFIG(tooltip)
        self.actionGroup.setToolTip(QCoreApplication.translate("MainWindow", u"Group selected annotations into one instance (Ctrl+G); split (Ctrl+G)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionGroup.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnnoTypeRectangle.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
        self.actionAnnoTypePolygon.setText(QCoreApplication.translate("MainWindow", u"Polygon", None))
        self.actionAnnoTypeRLEMask.setText(QCoreApplication.translate("MainWindow", u"RLE Mask", None))
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionChinese.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))
        self.actionFiles.setText(QCoreApplication.translate("MainWindow", u"Files", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionAnnotations.setText(QCoreApplication.translate("MainWindow", u"Annotations", None))
        self.actionLabels.setText(QCoreApplication.translate("MainWindow", u"Labels", None))
        self.actionRestore.setText(QCoreApplication.translate("MainWindow", u"Restore", None))
        self.actionFullScreen.setText(QCoreApplication.translate("MainWindow", u"Full screen", None))
#if QT_CONFIG(tooltip)
        self.actionFullScreen.setToolTip(QCoreApplication.translate("MainWindow", u"Full screen (F11)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionFullScreen.setStatusTip(QCoreApplication.translate("MainWindow", u"Enter/Exit full screen mode.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionFullScreen.setWhatsThis(QCoreApplication.translate("MainWindow", u"Enter/Exit full screen mode.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionFullScreen.setShortcut(QCoreApplication.translate("MainWindow", u"F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionAnnoTypeKeyPoint.setText(QCoreApplication.translate("MainWindow", u"KeyPoint", None))
        self.actionDockLeft.setText(QCoreApplication.translate("MainWindow", u"Left", None))
#if QT_CONFIG(tooltip)
        self.actionDockLeft.setToolTip(QCoreApplication.translate("MainWindow", u"Left (Ctrl+B)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDockLeft.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionDockRight.setText(QCoreApplication.translate("MainWindow", u"Right", None))
#if QT_CONFIG(tooltip)
        self.actionDockRight.setToolTip(QCoreApplication.translate("MainWindow", u"Right (Ctrl+Alt+B)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDockRight.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionDockBottom.setText(QCoreApplication.translate("MainWindow", u"Bottom", None))
#if QT_CONFIG(tooltip)
        self.actionDockBottom.setToolTip(QCoreApplication.translate("MainWindow", u"Bottom (Ctrl+J)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDockBottom.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuLang.setTitle(QCoreApplication.translate("MainWindow", u"Language", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
#if QT_CONFIG(tooltip)
        self.menuAnno_Type.setToolTip(QCoreApplication.translate("MainWindow", u"Select annotation type (Rectangle, Polygon, KeyPoint).", None))
#endif // QT_CONFIG(tooltip)
        self.menuAnno_Type.setTitle(QCoreApplication.translate("MainWindow", u"Anno Type", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.menuDocks.setTitle(QCoreApplication.translate("MainWindow", u"Docks", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.dock_infos.setWindowTitle(QCoreApplication.translate("MainWindow", u"Info", None))
        self.dock_annos.setWindowTitle(QCoreApplication.translate("MainWindow", u"Annos", None))
        self.dock_files.setWindowTitle(QCoreApplication.translate("MainWindow", u"Files", None))
        self.dock_labels.setWindowTitle(QCoreApplication.translate("MainWindow", u"Labels", None))
    # retranslateUi

